### ISSUE TITLE
main()

### ISSUE THREAD

**Issue by Monal5031** [aashutoshrathi/Basic-School-Management-System#1]
Tried executing main()
Inserted admin pass as "admin123"
runs infinite loop instead! Check it once

**Comment by aashutoshrathi** [comment]
No actually if you enter password in choice where you need to select 1 i.e. Enter password it will go on an infinite loop :dagger:

**Comment by Monal5031** [comment]
Wait I'll do some changes in it and make the loop go finite

**Comment by Monal5031** [comment]
Also the the feature to hide password using \* works only once!
If we enter wrong password once and try again \* dont work in student login

**Comment by Prakash2403** [comment]
I know it's late but if you guys are still doing this project and stuck somewhere, then feel free to ask for help.

**Comment by aashutoshrathi** [comment]
ok

**Comment by Prakash2403** [comment]
So, the issues which you have closed are solved or you have just closed them.
