### ISSUE TITLE
Having an issue in formation of student login file

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/Basic-School-Management-System#3]
I'm unable to search username and password for a student in student file entry

**Comment by Monal5031** [comment]
What you can do is.. take the username by user and search for that in the whole list line by line when found inside that condition make an array pass[] then fscanf of that password only when the username is found!
I am using the same technique to change the event name time info in my project!
Have a look at modifyName() modifyTime() modifyInfo() you will get it

**Comment by Monal5031** [comment]
http://stackoverflow.com/questions/20510718/moving-file-pointer-back-to-string-it-already-read

You can use this if you want to change the username as well
