### ISSUE TITLE
Password Function not working properly, it is printing something garbage in first value.. HELP !!

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/Basic-School-Management-System#5]
#include<stdio.h>

void main() {
   char password[25],ch;
   int i=0,j;

   puts("Enter password : ");

   while (1)
    {
      if (i < 0) {
         i = 0;
      }

      ch = getch();

      if (ch == 13)
         break;

      if (ch == 8)
      {
         printf("\b\b");
         i--;
         system("cls");
         puts("Enter password :");
         for(j=0;j<i;j++)
         printf("*");
         continue;
      }
      i++;
      password[i] = ch;
      ch = '*';
      printf("%c",ch);
   }

   password[i] = '\0';
   printf("\nPassword Entered : %s", password);

}

**Comment by Monal5031** [comment]
#include<stdio.h>

void main() {
char password[25],ch;
int i=0,j;

puts("Enter password : ");

while (1)
{
if (i < 0) {
i = 0;
}

  ch = getch();

  if (ch == 13)
     break;

  if (ch == 8)
  {
     printf("\b\b");
     i--;
     system("cls");
     puts("Enter password :");
     for(j=0;j<i;j++)
     printf("_");
     continue;
  }
  password[i] = ch;
  i++;
  ch = '_';
  printf("%c",ch);

}

password[i] = '\0';
printf("\nPassword Entered : %s", password);

}
